### PR TITLE
performance: only process image once

### PR DESCRIPTION
**Pull request by belohnung**

### CODE REVIEW

**Comment by RealMrCactus** [comment]
UwU

**Comment by rafa-br34** [comment]
I sucked Sidus's dick yesterday, tasted nice.

**Comment by Sidus-s** [comment]
He can only fit the tip tho, otherwise its too big

**Comment by rafa-br34** [comment]
> He can only fit the tip tho, otherwise its too big

facts ^^^^
but it's pretty cute when it's half erect

**Comment by RealMrCactus** [comment]
> > He can only fit the tip tho, otherwise its too big
> 
> facts ^^^^ but it's pretty cute when it's half erect

cap

**Comment by belohnung** [comment]
i stand in no affiliation with the people in this pull request

**Comment by rafa-br34** [comment]
> i stand in no affiliation with the people in this pull request

bet

**Comment by RealMrCactus** [comment]
> i stand in no affiliation with the people in this pull request

you literally asked me if you can make it for me

**Comment by RealMrCactus** [comment]
tbh these comments are like sexual harrasment

**Comment by RealMrCactus** [comment]
image
Bruh

**Comment by Sidus-s** [comment]
nahhhhhhhhh

**Comment by rafa-br34** [comment]
> tbh these comments are like sexual harassment

*proceeds to nuke all our accounts*
the sad part is that this will likely be tainted on our github history forever

**Comment by RealMrCactus** [comment]
> > tbh these comments are like sexual harassment
> 
> _proceeds to nuke all our accounts_ the sad part is that this will likely be tainted on our github history forever

your employer reading this 10 years from now: 👀

**Comment by Sidus-s** [comment]
yall comment alot, i wanna record this

**Comment by RealMrCactus** [comment]
> yall comment alot, i wanna record this

This is violation of my rights

**Comment by rafa-br34** [comment]
> yall comment alot, i wanna record this

ye a do a edit of it that'd be nice

**Comment by Sidus-s** [comment]
COMENTTTTTTTTTTTTTTT

**Comment by RealMrCactus** [comment]
why

**Comment by RealMrCactus** [comment]
image

**Comment by Sidus-s** [comment]
DO  IT

**Comment by Sidus-s** [comment]
ok

**Comment by RealMrCactus** [comment]
> ok

**Comment by RealMrCactus** [comment]
> > ok

**Comment by RealMrCactus** [comment]
> > > ok

**Comment by RealMrCactus** [comment]
> > > > ok

**Comment by RealMrCactus** [comment]
> > > > > ok

**Comment by rafa-br34** [comment]
omg

**Comment by rafa-br34** [comment]
brain damage be like:

**Comment by RealMrCactus** [comment]
> > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > >  ok

**Comment by RealMrCactus** [comment]
image

**Comment by Sidus-s** [comment]
go go go

**Comment by RealMrCactus** [comment]
github pr turned into discord

**Comment by rafa-br34** [comment]
LMAO IKR

> github pr turned into discord

**Pull request merged**
